runtime: java11
env: standard
instance_class: F2
inbound_services:
  - warmup
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  target_cpu_utilization: 0.7
  min_instances: 1
  max_instances: 5
service: pubsub

vpc_access_connector:
  name: "projects/jester-foxtrot/locations/us-central1/connectors/connect-to-sql"